#!/usr/bin/env bun
// Refresh ~/vault/api/PROVIDERS.md from ~/vault/api/models.json + live provider model lists.
// Run daily via cron (see SETUP.md) or manually after editing models.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";

const API_DIR = join(homedir(), "vault", "api");
const REGISTRY = join(API_DIR, "models.json");
const DOC = join(API_DIR, "PROVIDERS.md");

type ModelMeta = { intel?: number | null; notes?: string };
type Provider = {
  base: string;
  pass?: string;
  auth?: "bearer" | "anthropic";
  list?: string; // model-list URL; absent = static provider (no list API)
  probe_model?: string; // model id to ping via /chat/completions; absent = skip smoke test
  notes?: string;
  models?: Record<string, ModelMeta>; // optional: cli-proxy has no watchlist, just probe_model
};
type Registry = { providers: Record<string, Provider> };

type LiveModel = { id: string; ctx?: number; status?: string };

function passShow(path: string): string {
  return execFileSync("pass", ["show", path], { encoding: "utf8" }).trim().split("\n")[0];
}

// ponytail: tolerate the common list shapes ({data:[]},{models:[]},bare []) — extend when a provider breaks it
function extractModels(json: unknown): LiveModel[] {
  const j = json as Record<string, unknown>;
  const arr = Array.isArray(json) ? json : (j?.data ?? j?.models ?? j?.items ?? []);
  if (!Array.isArray(arr)) return [];
  return arr
    .map((e: Record<string, unknown>) =>
      typeof e === "string"
        ? { id: e as string }
        : {
            id: String(e.id ?? e.name ?? e.model ?? ""),
            ctx: (e.context_length ?? e.max_model_len ?? e.context_window) as number | undefined,
            status:
              e.hot === true ? "hot" : e.hot === false ? "cold" : ((e.status ?? e.model_class) as string | undefined),
          },
    )
    .filter((e) => e.id);
}

function authHeaders(p: Provider): Record<string, string> {
  const headers: Record<string, string> = { "content-type": "application/json" };
  if (!p.pass) return headers;
  const key = passShow(p.pass);
  if (p.auth === "anthropic") {
    headers["x-api-key"] = key;
    headers["anthropic-version"] = "2023-06-01";
  } else headers.Authorization = `Bearer ${key}`;
  return headers;
}

async function fetchLive(p: Provider): Promise<{ live: Map<string, LiveModel>; line: string }> {
  if (!p.list) return { live: new Map(), line: "static (no list API)" };
  try {
    const res = await fetch(p.list, { headers: authHeaders(p), signal: AbortSignal.timeout(30_000) });
    if (!res.ok) return { live: new Map(), line: `FETCH FAILED: HTTP ${res.status}` };
    const models = extractModels(await res.json());
    return { live: new Map(models.map((m) => [m.id, m])), line: `${models.length} models listed` };
  } catch (err) {
    return { live: new Map(), line: `FETCH FAILED: ${err}` };
  }
}

// ponytail: 1-token ping against p.base/chat/completions — catches list-up-but-quota-down (chutes 402)
// and CLI-proxy pool alias state (smart/fast failover). Skipped if probe_model unset.
async function chatSmoke(p: Provider): Promise<string> {
  if (!p.probe_model) return "skip";
  const url = `${p.base.replace(/\/$/, "")}/chat/completions`;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: authHeaders(p),
      body: JSON.stringify({
        model: p.probe_model,
        messages: [{ role: "user", content: "ping" }],
        max_tokens: 4,
      }),
      signal: AbortSignal.timeout(45_000),
    });
    if (res.ok) return `smoke OK (${p.probe_model})`;
    return `SMOKE FAILED: HTTP ${res.status} (${p.probe_model})`;
  } catch (err) {
    return `SMOKE FAILED: ${err}`;
  }
}

const reg: Registry = JSON.parse(readFileSync(REGISTRY, "utf8"));
const now = new Date().toISOString().slice(0, 16) + "Z";
const out: string[] = [
  "# API Providers — live status",
  "",
  `> GENERATED by \`arc-skills/skills/api-providers/refresh.ts\` — edit \`~/vault/api/models.json\`, never this file.`,
  `> Updated: ${now}. Key usage + routing guidance: \`/api-providers\` skill.`,
  "",
];

for (const [name, p] of Object.entries(reg.providers)) {
  const { live, line } = await fetchLive(p);
  const smoke = await chatSmoke(p);
  out.push(`## ${name}`, "");
  const keyBit = p.pass ? `key \`pass show ${p.pass}\` · ` : "";
  out.push(`\`${p.base}\` · ${keyBit}${line} (${now})`);
  if (smoke !== "skip") out.push(`> chat smoke: ${smoke} (${now})`);
  if (p.notes) out.push(`> ${p.notes}`);
  if (p.models && Object.keys(p.models).length) {
    out.push("", "| model | avail | warm/status | ctx | intel | notes |", "|---|---|---|---|---|---|");
    for (const [id, meta] of Object.entries(p.models)) {
      const m = live.get(id);
      const down = smoke.startsWith("SMOKE FAILED");
      const avail = !p.list ? "static" : line.startsWith("FETCH FAILED") ? "?" : down ? "✗ quota" : m ? "✓" : "✗";
      out.push(
        `| ${id} | ${avail} | ${m?.status ?? "-"} | ${m?.ctx ?? "-"} | ${meta.intel ?? "?"} | ${meta.notes ?? ""} |`,
      );
    }
  }
  out.push("");
}

mkdirSync(API_DIR, { recursive: true });
writeFileSync(DOC, out.join("\n"));
console.log(`wrote ${DOC}`);
